### PR TITLE
cdg_renderer: update to image 0.21

### PR DESCRIPTION
**Pull request by gdesmott**
I did some experiments and ported `cdg_renderer` to the new `image` API. In the end it wasn't needed as image 0.10 was enough for my needs but I figured it could still be useful if you'd like to move to the new version. If not feel free to close this PR.

I didn't port `qaraoke` itself as I was only using the renderer.

### CODE REVIEW

**Comment by sdroege** [comment]
It would be great to get this merged indeed. Version 0.10 is about 3 years old by now :)

**Comment by sdroege** [comment]
Also glutin is quite outdated, and other dependencies too. Seems worth going over the output of `cargo outdated` at some point :)

**Comment by sdroege** [comment]
@gdesmott seems like qaraoke only needs the version to be updated and then compiles. Maybe update that in this PR already?

**Comment by gdesmott** [comment]
Good idea, I've done that.

**Comment by thequux** [comment]
Sorry this one took longer; I was busy with work yesterday.

**Comment by gdesmott** [comment]
Great, thank you!
Can you please ping me when you'll push a new release so we can update the dep in our end as well?

**Comment by thequux** [comment]
Already done

**Comment by gdesmott** [comment]
Awesome, thank you so much.

**Comment by sdroege** [comment]
@gdesmott image 0.22 is released now, want to send another PR and also update the GStreamer plugin accordingly? Thanks :)

**Comment by gdesmott** [comment]
Here it is: https://github.com/thequux/qaraoke/pull/4

I'll do gst once this is released.

**Pull request merged**
